version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" 
    depends_on:
      - db
    env_file:
      - src/.env
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=ecommerce
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: